# Generated by Django 5.1.7 on 2025-03-16 18:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('art', models.ImageField(blank=True, upload_to='album_covers')),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('genre', models.CharField(choices=[('unknown', 'Unknown'), ('rock', 'Rock'), ('musical', 'Musical Theatre'), ('metal', 'Metal'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('rap', 'Rap')], default='unknown', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, default="This user hasn't provided a description yet.")),
                ('favourite_album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='album_rater.album')),
                ('liked_albums', models.ManyToManyField(related_name='liked_by', to='album_rater.album')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_followed', models.ManyToManyField(to='album_rater.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('rating_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='album_rater.album')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_rater.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_rater.userprofile'),
        ),
    ]
