# Generated by Django 5.0 on 2025-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_rater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateField(default='<built-in method today of type object at 0x00007FFF1D06E900>'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateField(default='<built-in method today of type object at 0x00007FFF1D06E900>'),
        ),
    ]
