# Generated by Django 5.0 on 2025-03-04 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_rater', '0003_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateField(default=datetime.date(2025, 3, 4)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateField(default=datetime.date(2025, 3, 4)),
        ),
    ]
