# Generated by Django 5.0 on 2025-03-04 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_rater', '0004_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 4, 10, 11, 31, 240462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 3, 4, 10, 11, 31, 240462, tzinfo=datetime.timezone.utc)),
        ),
    ]
