# Generated by Django 5.0 on 2025-03-04 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_rater', '0005_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
