# Generated by Django 5.0 on 2025-03-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_rater', '0006_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
