# Generated by Django 5.0 on 2025-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_rater', '0007_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='liked_albums',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='album_rater.album'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='users_followed',
            field=models.ManyToManyField(blank=True, to='album_rater.userprofile'),
        ),
    ]
