# Generated by Django 2.2.28 on 2025-03-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_rater', '0009_auto_20250319_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art',
            field=models.ImageField(upload_to='album_covers'),
        ),
    ]
